/*
 * Copyright 2018 tweerlei Wruck + Buchmeier GbR - http://www.tweerlei.de/
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.tweerlei.ermtools.dialect;

import java.sql.SQLException;

/**
 * Read output generated by SQL scripts
 * 
 * @author Robert Wruck
 */
public interface SQLScriptOutputReader
	{
	/**
	 * Enable output generation for subsequent statements
	 * @throws SQLException on error
	 */
	public void enable() throws SQLException;
	
	/**
	 * Disable output generation for subsequent statements
	 * @throws SQLException on error
	 */
	public void disable() throws SQLException;
	
	/**
	 * Fetch the output generated by the most recent statement
	 * @return Output
	 * @throws SQLException on error
	 */
	public String readOutput() throws SQLException;
	
	/**
	 * Close any created statements
	 * @throws SQLException on error
	 */
	public void close() throws SQLException;
	}
